SKILL_CAREER_MAP = {
    # IT & Software
    'python': 'Data Scientist',
    'java': 'Software Developer',
    'sql': 'Database Administrator',
    'html': 'Web Developer',
    'css': 'Frontend Developer',
    'javascript': 'Frontend Developer',
    'react': 'UI Developer',
    'angular': 'UI Developer',
    'node.js': 'Backend Developer',
    'flask': 'Backend Developer',
    'django': 'Backend Developer',
    'machine learning': 'ML Engineer',
    'deep learning': 'AI Engineer',
    'ai': 'AI Engineer',
    'nlp': 'NLP Engineer',
    'c++': 'Embedded Systems Developer',
    'c': 'Systems Programmer',
    'bash': 'Linux Administrator',
    'linux': 'System Administrator',
    'docker': 'DevOps Engineer',
    'kubernetes': 'Cloud Engineer',
    'aws': 'Cloud Architect',
    'azure': 'Cloud Solutions Architect',
    'git': 'Version Control Engineer',
    'android': 'Mobile App Developer',
    'ios': 'iOS Developer',
    'cybersecurity': 'Security Analyst',
    'penetration testing': 'Pen Tester',
    'blockchain': 'Blockchain Developer',
    'data analysis': 'Data Analyst',
    'r': 'Statistician',
    'excel': 'Business Analyst',
    'python': 'Software Engineer',
    'java': 'Software Developer',
    'c++': 'Systems Engineer',
    'c': 'Embedded Software Developer',
    'c#': '.NET Developer',
    'javascript': 'Frontend Developer',
    'typescript': 'Frontend Developer',
    'html': 'Web Developer',
    'css': 'UI Developer',
    'sass': 'UI Developer',
    'less': 'UI Developer',
    'bootstrap': 'Frontend Developer',
    'jquery': 'Frontend Developer',
    'react': 'React Developer',
    'vue.js': 'Vue Developer',
    'angular': 'Angular Developer',
    'next.js': 'Full Stack Developer',
    'nuxt.js': 'Web Developer',
    'node.js': 'Backend Developer',
    'express.js': 'Node.js Developer',
    'nestjs': 'Backend Developer',
    'fastapi': 'Python Developer',
    'flask': 'Python Developer',
    'django': 'Python Web Developer',
    'spring': 'Java Backend Developer',
    'spring boot': 'Java Backend Developer',
    'hibernate': 'Java Developer',
    'struts': 'Java Web Developer',
    'php': 'PHP Developer',
    'laravel': 'Laravel Developer',
    'codeigniter': 'PHP Developer',
    'symfony': 'PHP Developer',
    'mysql': 'Database Engineer',
    'postgresql': 'Database Administrator',
    'sqlite': 'Embedded DB Developer',
    'mongodb': 'NoSQL Developer',
    'redis': 'Caching Engineer',
    'cassandra': 'Big Data Engineer',
    'oracle': 'Oracle DBA',
    'sql server': 'MSSQL DBA',
    'graphQL': 'API Developer',
    'rest api': 'Backend Developer',
    'soap': 'Web Services Developer',
    'git': 'Version Control Specialist',
    'github': 'DevOps Support Engineer',
    'bitbucket': 'DevOps Engineer',
    'gitlab': 'DevOps Engineer',
    'svn': 'Source Control Engineer',
    'docker': 'DevOps Engineer',
    'kubernetes': 'Cloud Infrastructure Engineer',
    'terraform': 'Cloud Automation Engineer',
    'ansible': 'DevOps Engineer',
    'jenkins': 'CI/CD Engineer',
    'circleci': 'CI/CD Engineer',
    'travis ci': 'CI/CD Developer',
    'aws': 'AWS Cloud Engineer',
    'azure': 'Azure Solutions Architect',
    'gcp': 'Google Cloud Engineer',
    'cloudformation': 'Cloud Infrastructure Developer',
    'powershell': 'Scripting Engineer',
    'bash': 'Linux Administrator',
    'linux': 'System Administrator',
    'unix': 'Unix Administrator',
    'windows server': 'Windows Admin',
    'vmware': 'Virtualization Engineer',
    'virtualbox': 'Virtualization Technician',
    'hyper-v': 'Hyper-V Specialist',
    'nmap': 'Network Security Analyst',
    'wireshark': 'Packet Analyst',
    'burp suite': 'Security Analyst',
    'metasploit': 'Penetration Tester',
    'nessus': 'Security Consultant',
    'kali linux': 'Ethical Hacker',
    'penetration testing': 'Security Tester',
    'vulnerability assessment': 'Security Analyst',
    'firewall': 'Network Engineer',
    'load balancing': 'Network Administrator',
    'switching': 'Network Technician',
    'routing': 'Network Engineer',
    'ccna': 'Network Associate',
    'ccnp': 'Network Professional',
    'network monitoring': 'NOC Engineer',
    'zabbix': 'Monitoring Engineer',
    'nagios': 'System Monitoring Engineer',
    'splunk': 'Security Monitoring Analyst',
    'prometheus': 'Site Reliability Engineer',
    'grafana': 'Observability Engineer',
    'elastic stack': 'Log Analyst',
    'elk': 'Log Aggregation Engineer',
    'jira': 'Project Coordinator',
    'confluence': 'Documentation Specialist',
    'service now': 'ITSM Analyst',
    'bmc remedy': 'IT Support Engineer',
    'powershell scripting': 'Windows Automation Engineer',
    'shell scripting': 'System Automation Developer',
    'vbscript': 'Legacy Script Developer',
    'python scripting': 'Automation Engineer',
    'regex': 'Text Processing Specialist',
    'json': 'Data Integrator',
    'yaml': 'Config Engineer',
    'xml': 'Data Format Specialist',
    'excel vba': 'Excel Developer',
    'access': 'MS Access Developer',
    'outlook automation': 'Workflow Engineer',
    'sap basis': 'SAP Basis Consultant',
    'sap abap': 'SAP ABAP Developer',
    'sap fico': 'SAP Finance Consultant',
    'crm': 'CRM Administrator',
    'erp': 'ERP Analyst',
    'oracle fusion': 'Oracle Consultant',
    'dynamics 365': 'Dynamics Developer',
    'salesforce': 'Salesforce Admin',
    'salesforce lightning': 'Salesforce Developer',
    'appium': 'Mobile Automation Tester',
    'selenium': 'Test Automation Engineer',
    'jmeter': 'Performance Tester',
    'loadrunner': 'Load Testing Engineer',
    'postman': 'API Tester',
    'soapui': 'Web Services Tester',
    'pytest': 'Python QA Engineer',
    'testng': 'Java Automation Tester',
    'cucumber': 'BDD Tester',
    'jira xray': 'Test Management Engineer',
    'test rail': 'Test Coordinator',
    'bugzilla': 'Bug Tracking Engineer',
    'uxpin': 'UX Designer',
    'balsamiq': 'Wireframe Designer',
    'axure': 'UX Researcher',
    'mockplus': 'Prototyping Specialist',
    'figma': 'Product Designer',
    'miro': 'Team Collaboration Analyst',
    'notion': 'Product Coordinator',
    'asana': 'Task Manager',
    'clickup': 'Workflow Manager',
    'monday.com': 'Project Scheduler',
    'power bi': 'BI Developer',
    'tableau': 'Data Visualizer',
    'qlikview': 'Business Intelligence Analyst',
    'looker': 'BI Consultant',
    'data warehouse': 'ETL Developer',
    'data lake': 'Data Lake Architect',
    'etl': 'Data Engineer',
    'airflow': 'Data Pipeline Developer',
    'snowflake': 'Cloud Data Engineer',
    'databricks': 'Lakehouse Engineer',
    'hadoop': 'Big Data Developer',
    'spark': 'Distributed Systems Developer',
    'kafka': 'Streaming Data Engineer',
    'flink': 'Real-time Data Engineer',
    'redis': 'Cache Engineer',
    'memcached': 'In-Memory DB Admin',
    'apache storm': 'Stream Processing Engineer',
    'zookeeper': 'Cluster Coordinator',
    'docker swarm': 'Container Orchestration Specialist',
    'helm': 'Kubernetes Package Manager',
    'vault': 'Secrets Manager',
    'consul': 'Service Discovery Engineer',
    'puppet': 'Config Management Engineer',
    'chef': 'Infrastructure Automation Engineer',
    'vagrant': 'Virtual Environment Specialist',
    'ansible tower': 'DevOps Operator',
    'cloudwatch': 'AWS Monitoring Engineer',
    'cloudtrail': 'Cloud Audit Specialist',
    'azure devops': 'CI/CD Cloud Engineer',
    'gke': 'GCP Kubernetes Specialist',
    'eks': 'AWS Kubernetes Specialist',
    'aks': 'Azure Kubernetes Engineer',
    'api gateway': 'API Gateway Specialist',
    'lambda': 'Serverless Developer',
    'appsync': 'GraphQL Cloud Engineer',
    'cloudflare': 'Edge Network Engineer',
    'vercel': 'Deployment Engineer',
    'netlify': 'Frontend Hosting Specialist',

    # Design & Creative
    'photoshop': 'Graphic Designer',
    'illustrator': 'Vector Artist',
    'indesign': 'Layout Designer',
    'coreldraw': 'Print Designer',
    'figma': 'UI/UX Designer',
    'adobe xd': 'UI Designer',
    'sketch': 'UX Designer',
    'canva': 'Marketing Designer',
    'lightroom': 'Photo Editor',
    'premiere pro': 'Video Editor',
    'after effects': 'Motion Designer',
    'final cut pro': 'Film Editor',
    'davinci resolve': 'Color Grading Specialist',
    'blender': '3D Artist',
    'maya': '3D Modeler',
    'cinema 4d': 'Motion Graphics Artist',
    'zbrush': '3D Sculptor',
    'animation': 'Animator',
    'stop motion': 'Stop Motion Animator',
    'typography': 'Type Designer',
    'branding': 'Brand Designer',
    'logo design': 'Logo Specialist',
    'infographics': 'Infographic Designer',
    'brochure design': 'Print Designer',
    'web design': 'Web Designer',
    'responsive design': 'Responsive Web Designer',
    'wireframing': 'UX Designer',
    'prototyping': 'Product Designer',
    'user research': 'UX Researcher',
    'accessibility': 'Inclusive Designer',
    'storyboarding': 'Storyboard Artist',
    'visual storytelling': 'Visual Designer',
    'creative direction': 'Creative Director',
    'art direction': 'Art Director',
    'photography': 'Photographer',
    'videography': 'Videographer',
    'video editing': 'Video Editor',
    'audio editing': 'Audio Editor',
    'voice over': 'Voice Talent',
    'script writing': 'Scriptwriter',
    'content creation': 'Content Creator',
    'social media design': 'Social Media Designer',
    'presentation design': 'Pitch Deck Designer',
    'fashion design': 'Fashion Designer',
    'interior design': 'Interior Designer',
    'exhibition design': 'Exhibition Designer',
    'print production': 'Print Production Artist',
    '3d visualization': '3D Visualizer',
    'digital painting': 'Digital Artist',
    'pixel art': 'Pixel Artist',
    'concept art': 'Concept Artist',
    'game art': 'Game Artist',

    # Business & Marketing
    'seo': 'SEO Specialist',
    'sem': 'PPC Specialist',
    'google ads': 'Ad Campaign Manager',
    'facebook ads': 'Social Media Marketer',
    'instagram marketing': 'Social Media Strategist',
    'linkedin marketing': 'B2B Marketing Specialist',
    'content marketing': 'Content Marketing Manager',
    'email marketing': 'Email Campaign Manager',
    'sms marketing': 'Mobile Marketing Executive',
    'marketing automation': 'Marketing Automation Specialist',
    'hubspot': 'Inbound Marketing Specialist',
    'salesforce': 'CRM Executive',
    'zoho crm': 'CRM Analyst',
    'product marketing': 'Product Marketing Manager',
    'market research': 'Market Analyst',
    'branding': 'Brand Manager',
    'brand strategy': 'Brand Strategist',
    'copywriting': 'Copywriter',
    'advertising': 'Advertising Executive',
    'media buying': 'Media Buyer',
    'public relations': 'PR Executive',
    'event marketing': 'Event Coordinator',
    'trade marketing': 'Trade Marketing Manager',
    'b2b sales': 'B2B Sales Executive',
    'b2c sales': 'Retail Sales Manager',
    'inside sales': 'Inside Sales Rep',
    'outbound sales': 'Field Sales Executive',
    'telemarketing': 'Telemarketing Executive',
    'cold calling': 'Lead Generation Executive',
    'lead generation': 'Lead Gen Specialist',
    'conversion optimization': 'CRO Specialist',
    'growth hacking': 'Growth Marketer',
    'affiliate marketing': 'Affiliate Manager',
    'influencer marketing': 'Influencer Campaign Manager',
    'social media': 'Social Media Executive',
    'community management': 'Community Manager',
    'campaign management': 'Campaign Manager',
    'digital analytics': 'Digital Analyst',
    'web analytics': 'Web Analyst',
    'google analytics': 'Google Analytics Specialist',
    'excel': 'Marketing Analyst',
    'powerpoint': 'Marketing Presenter',
    'presentation design': 'Pitch Deck Designer',
    'customer acquisition': 'Acquisition Manager',
    'customer retention': 'Retention Marketing Manager',
    'pricing strategy': 'Pricing Analyst',
    'go to market': 'Go-To-Market Manager',
    'channel marketing': 'Channel Marketing Executive',
    'shopper marketing': 'Retail Marketing Analyst',
    'loyalty programs': 'Loyalty Manager',
    'surveys': 'Survey Analyst',

    # Education & Training
    'teaching': 'Educator',
    'curriculum development': 'Curriculum Designer',
    'instructional design': 'Instructional Designer',
    'lesson planning': 'Lesson Planner',
    'assessment design': 'Assessment Specialist',
    'educational technology': 'EdTech Specialist',
    'e-learning': 'Online Course Developer',
    'moodle': 'Learning Platform Administrator',
    'blackboard': 'Academic Platform Coordinator',
    'canvas lms': 'Learning Management Consultant',
    'google classroom': 'Online Educator',
    'zoom teaching': 'Virtual Instructor',
    'webinar hosting': 'Education Facilitator',
    'student engagement': 'Engagement Specialist',
    'classroom management': 'Classroom Manager',
    'pedagogy': 'Teaching Methodologist',
    'andragogy': 'Adult Educator',
    'training delivery': 'Corporate Trainer',
    'train the trainer': 'Trainer Coach',
    'presentation skills': 'Training Facilitator',
    'workshop facilitation': 'Workshop Leader',
    'public speaking': 'Public Speaker',
    'communication skills': 'Soft Skills Trainer',
    'academic writing': 'Academic Coach',
    'research guidance': 'Research Supervisor',
    'subject expertise': 'Subject Matter Expert',
    'curriculum mapping': 'Education Strategist',
    'outcome-based education': 'OBE Coordinator',
    'experiential learning': 'Learning Experience Designer',
    'gamification': 'Learning Gamification Expert',
    'interactive content': 'Interactive Content Developer',
    'quiz creation': 'Assessment Content Developer',
    'training need analysis': 'TNA Consultant',
    'online tutoring': 'Virtual Tutor',
    'home tutoring': 'Personal Tutor',
    'special education': 'Special Needs Educator',
    'inclusive education': 'Inclusive Learning Coach',
    'educational psychology': 'Education Psychologist',
    'career counseling': 'Career Coach',
    'student mentoring': 'Academic Mentor',
    'internship coordination': 'Placement Officer',
    'university liaison': 'Academic Liaison Officer',
    'school administration': 'School Administrator',
    'education policy': 'Policy Researcher',
    'faculty development': 'Faculty Trainer',
    'education research': 'Education Researcher',
    'education consultancy': 'Education Consultant',
    'learning strategies': 'Learning Strategist',
    'instructional material': 'Instructional Writer',
    'study skills': 'Study Skills Coach',
    'time management training': 'Time Management Trainer',

    # Finance & Accounting
    'accounting': 'Accountant',
    'bookkeeping': 'Bookkeeper',
    'tally': 'Accounts Executive',
    'gst': 'Tax Accountant',
    'vat': 'Tax Specialist',
    'sap fico': 'SAP FICO Consultant',
    'sap mm': 'SAP Materials Consultant',
    'sap hana': 'SAP Analyst',
    'quickbooks': 'Accounting Software Specialist',
    'ms excel': 'Financial Analyst',
    'excel modeling': 'Financial Modeler',
    'reconciliation': 'Accounts Reconciliation Analyst',
    'audit': 'Auditor',
    'financial statements': 'Financial Reporting Analyst',
    'income tax': 'Tax Consultant',
    'balance sheet': 'Finance Officer',
    'profit and loss': 'Finance Executive',
    'ledger': 'Ledger Accountant',
    'bank reconciliation': 'Banking Analyst',
    'payroll': 'Payroll Executive',
    'investment analysis': 'Investment Analyst',
    'budgeting': 'Budget Analyst',
    'forecasting': 'Forecast Analyst',
    'variance analysis': 'Cost Analyst',
    'cost accounting': 'Cost Accountant',
    'internal audit': 'Internal Auditor',
    'external audit': 'External Auditor',
    'ifrs': 'IFRS Specialist',
    'gaap': 'GAAP Consultant',
    'statutory compliance': 'Compliance Officer',
    'risk analysis': 'Risk Analyst',
    'equity research': 'Equity Research Analyst',
    'portfolio management': 'Portfolio Manager',
    'financial planning': 'Financial Planner',
    'fund accounting': 'Fund Accountant',
    'mergers and acquisitions': 'M&A Analyst',
    'valuation': 'Valuation Analyst',
    'derivatives': 'Derivatives Analyst',
    'insurance': 'Insurance Advisor',
    'tax planning': 'Tax Planner',
    'treasury': 'Treasury Analyst',
    'cash flow': 'Cash Flow Analyst',
    'erp systems': 'ERP Analyst',
    'zoho books': 'Zoho Accountant',
    'compliance': 'Compliance Analyst',
    'securities': 'Securities Analyst',
    'financial modelling': 'Finance Modeler',
    'stock market': 'Stock Analyst',
    'credit analysis': 'Credit Analyst',
    'loan processing': 'Loan Officer',
    'mutual funds': 'Mutual Fund Analyst',

    # Healthcare
    'nursing': 'Nurse',
    'patient care': 'Care Assistant',
    'first aid': 'First Aid Technician',
    'emergency care': 'Emergency Technician',
    'clinical research': 'Clinical Research Associate',
    'medical transcription': 'Medical Transcriptionist',
    'medical billing': 'Billing Specialist',
    'medical coding': 'Medical Coder',
    'icd-10': 'Health Coder',
    'cpt coding': 'Medical Coding Analyst',
    'pharmacy': 'Pharmacist',
    'dispensing': 'Pharmacy Assistant',
    'pathology': 'Pathologist',
    'radiology': 'Radiologist',
    'x-ray': 'Radiographer',
    'ct scan': 'CT Technician',
    'mri': 'MRI Technician',
    'ecg': 'ECG Technician',
    'lab technology': 'Lab Technician',
    'phlebotomy': 'Phlebotomist',
    'dental assistant': 'Dental Assistant',
    'dental hygiene': 'Dental Hygienist',
    'physiotherapy': 'Physiotherapist',
    'occupational therapy': 'Occupational Therapist',
    'speech therapy': 'Speech Therapist',
    'mental health': 'Mental Health Counselor',
    'counseling': 'Health Counselor',
    'psychology': 'Clinical Psychologist',
    'healthcare management': 'Healthcare Administrator',
    'hospital administration': 'Hospital Admin Executive',
    'medical equipment': 'Biomedical Engineer',
    'surgical technology': 'Surgical Technologist',
    'anesthesia technology': 'Anesthesia Technician',
    'veterinary': 'Veterinary Technician',
    'nutrition': 'Nutritionist',
    'diet planning': 'Dietitian',
    'homeopathy': 'Homeopathic Doctor',
    'ayurveda': 'Ayurvedic Practitioner',
    'general medicine': 'General Physician',
    'pediatrics': 'Pediatrician',
    'cardiology': 'Cardiologist',
    'neurology': 'Neurologist',
    'orthopedics': 'Orthopedic Surgeon',
    'gynecology': 'Gynecologist',
    'dermatology': 'Dermatologist',
    'urology': 'Urologist',
    'oncology': 'Oncologist',
    'infectious diseases': 'Infection Control Specialist',
    'health education': 'Health Educator',

    # Engineering & Manufacturing
    'mechanical engineering': 'Mechanical Engineer',
    'thermodynamics': 'Thermal Engineer',
    'fluid mechanics': 'Fluid Systems Engineer',
    'hvac': 'HVAC Engineer',
    'cad': 'CAD Designer',
    'solidworks': 'Mechanical Design Engineer',
    'autocad': 'Drafting Engineer',
    'ansys': 'Simulation Engineer',
    'catia': 'Automotive Design Engineer',
    'creo': 'Product Design Engineer',
    'matlab': 'Signal Processing Engineer',
    'cam': 'CAM Engineer',
    'fea': 'Finite Element Analyst',
    'plc programming': 'Automation Engineer',
    'scada': 'SCADA Engineer',
    'embedded systems': 'Embedded Engineer',
    'circuit design': 'Electronics Engineer',
    'pcb design': 'PCB Designer',
    'electrical engineering': 'Electrical Engineer',
    'control systems': 'Control Systems Engineer',
    'power systems': 'Power Engineer',
    'transformers': 'Electrical Design Engineer',
    'switchgear': 'Power Systems Engineer',
    'civil engineering': 'Civil Engineer',
    'structural analysis': 'Structural Engineer',
    'etabs': 'Structure Designer',
    'staad pro': 'Structural Design Engineer',
    'construction management': 'Site Engineer',
    'surveying': 'Survey Engineer',
    'highway engineering': 'Transportation Engineer',
    'quantity surveying': 'Quantity Surveyor',
    'estimation': 'Cost Estimator',
    'piping': 'Piping Design Engineer',
    'manufacturing': 'Production Engineer',
    'lean manufacturing': 'Lean Engineer',
    'six sigma': 'Process Improvement Analyst',
    'kaizen': 'Continuous Improvement Engineer',
    'quality control': 'Quality Inspector',
    'quality assurance': 'QA Engineer',
    'iso standards': 'Compliance Engineer',
    'maintenance': 'Maintenance Engineer',
    'cnc': 'CNC Programmer',
    'mechatronics': 'Mechatronics Engineer',
    'robotics': 'Robotics Engineer',
    'industrial engineering': 'Industrial Engineer',
    'materials science': 'Materials Engineer',
    'metallurgy': 'Metallurgical Engineer',
    'nanotechnology': 'Nanotech Engineer',
    'aerospace': 'Aerospace Engineer',
    'automobile': 'Automobile Engineer',
    'marine engineering': 'Marine Engineer',


    # Media & Communication
    'journalism': 'Journalist',
    'content writing': 'Content Writer',
    'blogging': 'Blogger',
    'script writing': 'Script Writer',
    'editing': 'Content Editor',
    'voice over': 'Voice Artist',

    # Law & Public Services
    'legal research': 'Legal Associate',
    'contract review': 'Corporate Lawyer',
    'litigation': 'Legal Executive',
    'policy writing': 'Policy Analyst',
    'government documentation': 'Administrative Officer',

    # General & Soft Skills
    'communication': 'HR Executive',
    'team management': 'Team Leader',
    'leadership': 'Operations Manager',
    'problem solving': 'Analyst',
    'customer service': 'Customer Support Executive',
    'ms office': 'Office Administrator',
    'project management': 'Project Manager',
    'time management': 'Team Coordinator',
    'multitasking': 'Operations Executive'
}